#!/usr/bin/env bash
# Builds and runs every solution. A solution earns its points only if it
# builds and runs to completion with exit status 0 (no failed assertion).
# Generated by Claude. Please report bugs to tpalit at ucdavis dot edu.

cd "$(dirname "$0")" || exit 1
ROOT="$(pwd)"
LOG_DIR="$(mktemp -d)"
TOTAL=0
MAX=0
EXTRA=0
EXTRA_MAX=0

run_cpp() {
    local build_dir="$LOG_DIR/cpp-build"
    cmake -S . -B "$build_dir" -DCMAKE_BUILD_TYPE=Debug &&
        cmake --build "$build_dir" &&
        "$build_dir/configuration"
}

run_java() {
    mvn -q clean package &&
        java -ea -jar target/*.jar
}

run_python() {
    python3 main.py
}

run_rust() {
    cargo run -q
}

# grade <label> <points> <directory> <run function> [extra]
grade() {
    local label="$1" points="$2" dir="$3" runner="$4" kind="$5"
    local log="$LOG_DIR/$(echo "$label" | tr ' /' '__').log"
    local status earned

    (cd "$ROOT/$dir" && "$runner") >"$log" 2>&1
    status=$?

    if [ $status -eq 0 ]; then
        earned=$points
        printf "PASS  %-14s %4s / %s\n" "$label" "$earned" "$points"
    else
        earned=0
        printf "FAIL  %-14s %4s / %s   (exit status %d, log: %s)\n" "$label" "$earned" "$points" "$status" "$log"
        tail -n 5 "$log" | sed 's/^/        /'
    fi
    if [ "$kind" = "extra" ]; then
        EXTRA=$(awk "BEGIN { print $EXTRA + $earned }")
        EXTRA_MAX=$(awk "BEGIN { print $EXTRA_MAX + $points }")
    else
        TOTAL=$(awk "BEGIN { print $TOTAL + $earned }")
        MAX=$(awk "BEGIN { print $MAX + $points }")
    fi
}

grade "A Java"   0.5 PartA/Java   run_java
grade "A C++"    1   PartA/C++    run_cpp
grade "A Python" 1   PartA/Python run_python
grade "B Java"   0.5 PartB/Java   run_java
grade "B Python" 1   PartB/Python run_python
grade "C Java"   1   PartC/Java   run_java
grade "C Rust (EC)" 1 PartC/Rust   run_rust extra

echo
echo "Total: $TOTAL / $MAX"
echo "Extra credit: $EXTRA / $EXTRA_MAX"
echo
echo "Note: these points assume full credit for your answers to the written"
echo "questions, which are graded separately."
[ "$TOTAL" = "$MAX" ]
